---
title: "Coursera Reproducible Research Project 1"
author: "Andrea Gustafsen"
date: "12/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1 Loading and preprocessing the data

```{r, message=FALSE}
library(tidyverse)
# 1 load the data
data <- read_csv("activity.csv")
```

## 2 What is mean total number of steps taken per day?

```{r}
#remove NAs for this part of the assignment
data_comp <- drop_na(data)

# 1. summarise total number of steps each day
daily_steps <- data_comp %>% 
                group_by(date) %>% 
                summarise(daily_steps = sum(steps))

# 2. histogram for total number of steps each day
par(mfrow = c(1,1))
hist(daily_steps$daily_steps,
     main = "Daily Steps",
     xlab = "Daily steps")

# 3. Mean and median number of steps taken each day
daily_steps %>% 
        summarise(mean = mean(daily_steps),
                  median = median(daily_steps))
```

## What is the average daily activity pattern?
```{r}
# 4. Time series plot of the average number of steps taken
interval_avg <- data %>% 
                    group_by(interval) %>% 
                    summarise(mean_steps = mean(steps, na.rm = TRUE))

plot(interval_avg$interval, interval_avg$mean_steps, type = "l",
     col = "blue",
     main = "Average number of steps during day: 5-minutes intervals",
     xlab = "5-minute interval",
     ylab = "mean steps")


# 5. Find the 5-minute interval that, on average, contains the maximum number of steps
interval_avg %>% 
    filter(mean_steps == max(mean_steps))
```

## Imputing missing values
```{r}
# Code to describe and show a strategy for imputing missing data

# 1. calculate total number of missing values
sum(is.na(data))


# 2. will use simple mean imputation, imputing with mean for each interval
# dataset with imputed values
data_imputed <- data 

#data with NA's removed
data_no_missing <- subset(data, !is.na(data$steps))

# index for obs with missing values
index_missing <- is.na(data$steps)

# calculate mean for each interval
interval_avg <-tapply(data_no_missing$steps, data_no_missing$interval, mean, simplify = TRUE)

# 3. impute the mean into the new dataset 'data_imputed'
data_imputed$steps[index_missing] <- interval_avg[as.character(data_imputed$interval[index_missing])]

# 4. Histogram of the total number of steps taken each day after missing values are imputed
daily_steps_imputed <- data_imputed %>% 
                            group_by(date) %>% 
                            summarise(daily_steps = sum(steps))

hist(daily_steps_imputed$daily_steps,
     main = "Daily steps after imputing missing values",
     xlab = "daily steps")

# get mean and median for daily steps after imputation
daily_steps_imputed <- data_imputed %>% 
                            group_by(date) %>% 
                            summarise(daily_steps = sum(steps))
              
daily_steps_imputed %>% 
              summarise(mean = mean(daily_steps),
                        median = median(daily_steps))
```
## Are there differences in activity patterns between weekdays and weekends?

```{r}
# 8. Panel plot comparing the average number of steps taken per 5-minute interval across weekdays and weekends

# function weekdays() returns what day a certain date is
# use ifelse to make column indicating weekday or weekend
data_imputed$day <- ifelse(weekdays(data_imputed$date) == "Saturday" | weekdays(data_imputed$date) == "Sunday", "Weekend", "Weekday")

weekday_data <- data_imputed %>% 
                 group_by(day, interval) %>% 
                 summarise(mean_steps = mean(steps))

# make plot
ggplot(weekday_data, aes(x = interval, y = mean_steps)) +
    geom_line() +
    facet_wrap(~day, ncol = 1) +
    ylim(0, 300) +
    labs(title = "Average number of steps taken per 5-minute interval")

```

